package org.atlas.gateway.core.exceptions;

public enum GatewayErrorCode {

	INTERNAL_ERROR,
	OPERATION_NOT_SUPPORTED,
	CLOUD_CONNECTION_ERROR,
	WSN_CONNECTION_ERROR,
	MEDIATOR_ERROR,
	DATABASE_ERROR,
	TIMED_OUT
	
}
